### ISSUE TITLE
Flag of the countries within the United Kingdom are missing

### ISSUE THREAD

**Issue by glenh** [Worldremit/flags#1]
![flag_of_scotland svg](https://cloud.githubusercontent.com/assets/1394855/20620099/effb2834-b2ef-11e6-9ca7-841f0db45e24.png)

**Comment by joshdjuric** [comment]
@glenh Scotland has arrived.

**Comment by glenh** [comment]
Sorry @joshdjuric just noticed my notification for this - Brilliant - thanks for adding them 👍
